source 'https://github.com/CocoaPods/Specs.git'

platform :ios ,'10.0'
inhibit_all_warnings! # 这个除去第三方库的警告
use_modular_headers!

target 'LeetcodeDemo' do
    
pod 'Masonry'
pod 'MJExtension'
pod 'YBImageBrowser'

end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
    end
end
